Controllers/CourseController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SchoolApp.Data.Abstract;
using SchoolApp.Entity;

namespace SchoolApp.Controllers
{
    public class CourseController : Controller
    {
        private ICourseRepository _courseRepository;
        private ILecturerRepository _lecturerRepository;
        public CourseController(ICourseRepository courseRepository, ILecturerRepository lecturerRepository)
        {
            _courseRepository = courseRepository;
            _lecturerRepository = lecturerRepository;
        }

        public async Task<IActionResult> Index()
        {
            return View(await _courseRepository.Courses.Include(c => c.Lecturer).ToListAsync());
        }
        [HttpGet]
        public IActionResult Create()
        {
            FillSelectList();
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(Course course)
        {
            if (ModelState.IsValid)
            {
                await _courseRepository.CreateCourse(course);
                return RedirectToAction("Index");

            }
            FillSelectList(course);
            return View(course);
        }
        [HttpGet]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var course = await _courseRepository.Courses.FirstOrDefaultAsync(s => s.Id == id);
            if (course == null)
            {
                return NotFound();
            }
            FillSelectList(course);
            return View(course);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(Course course)
        {
            if (ModelState.IsValid)
            {
                await _courseRepository.EditCourse(course);
                return RedirectToAction("Index");
            }
            return View(course);
        }

        [HttpGet]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var course = await _courseRepository.Courses.Include(x => x.Enrollments).ThenInclude(x => x.Student).FirstOrDefaultAsync(s => s.Id == id);
            if (course == null)
            {
                return NotFound();
            }
            return View(course);
        }
        [HttpPost]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            await _courseRepository.DeleteCourse((int)id);
            return RedirectToAction("Index");
        }

        public void FillSelectList(Course course = null!)
        {
            ViewBag.LecturerItems = new SelectList(_lecturerRepository.Lecturers.Select(l => new { Id = l.Id, FullName = $"{l.FirstName} {l.LastName}" }), "Id", "FullName", course != null ? course.LecturerId : null);
        }
    }
}

Controllers/EnrollmentController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SchoolApp.Data.Abstract;
using SchoolApp.Entity;

namespace SchoolApp.Controllers
{
    public class EnrollmentController : Controller
    {
        private IEnrollmentRepository _enrollmentRepository;
        private ICourseRepository _courseRepository;
        private IStudentRepository _studentRepository;
        public EnrollmentController(IEnrollmentRepository enrollmentRepository, ICourseRepository courseRepository, IStudentRepository studentRepository)
        {
            _enrollmentRepository = enrollmentRepository;
            _courseRepository = courseRepository;
            _studentRepository = studentRepository;
        }

        public async Task<IActionResult> Index()
        {
            return View(await _enrollmentRepository.Enrollments.Include(c => c.Course).Include(s => s.Student).ToListAsync());
        }
        [HttpGet]
        public IActionResult Create()
        {
            FillSelectList();
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(Enrollment enrollment)
        {
            if (ModelState.IsValid)
            {
                await _enrollmentRepository.CreateEnrollment(enrollment);
                return RedirectToAction("Index");
            }
            return View(enrollment);
        }
        [HttpGet]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var enrollment = await _enrollmentRepository.Enrollments.FirstOrDefaultAsync(s => s.Id == id);
            if (enrollment == null)
            {
                return NotFound();
            }
            FillSelectList(enrollment);
            return View(enrollment);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(Enrollment enrollment)
        {
            if (ModelState.IsValid)
            {
                await _enrollmentRepository.EditEnrollment(enrollment);
                return RedirectToAction("Index");
            }
            FillSelectList(enrollment);
            return View(enrollment);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            await _enrollmentRepository.DeleteEnrollment((int)id);
            return RedirectToAction("Index");
        }
        public void FillSelectList(Enrollment enrollment = null!)
        {
            ViewBag.CourseItems = new SelectList(_courseRepository.Courses.Select(l => new { CourseId = l.Id, FullName = $"{l.Code} - {l.Name}" }), "CourseId", "FullName", enrollment != null ? enrollment.CourseId : null);
            ViewBag.StudentItems = new SelectList(_studentRepository.Students.Select(l => new { StudentId = l.Id, FullName = $"{l.FirstName} - {l.LastName}" }), "StudentId", "FullName", enrollment != null ? enrollment.StudentId : null);


        }
    }
}

Controllers/LecturerController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SchoolApp.Data.Abstract;
using SchoolApp.Entity;

namespace SchoolApp.Controllers
{
    public class LecturerController : Controller
    {
        private ILecturerRepository _lecturerRepository;
        public LecturerController(ILecturerRepository lecturerRepository)
        {
            _lecturerRepository = lecturerRepository;
        }

        public async Task<IActionResult> Index()
        {

            return View(await _lecturerRepository.Lecturers.ToListAsync());
        }
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(Lecturer lecturer)
        {
            if (ModelState.IsValid)
            {
                await _lecturerRepository.CreateLecturer(new Lecturer
                {
                    FirstName = lecturer.FirstName,
                    LastName = lecturer.LastName
                });
                return RedirectToAction("Index");
            }
            return View(lecturer);
        }
        [HttpGet]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var lecturer = await _lecturerRepository.Lecturers.FirstOrDefaultAsync(s => s.Id == id);
            if (lecturer == null)
            {
                return NotFound();
            }
            return View(lecturer);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(Lecturer lecturer)
        {
            if (ModelState.IsValid)
            {
                await _lecturerRepository.EditLecturer(lecturer);
                return RedirectToAction("Index");
            }
            return View(lecturer);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            await _lecturerRepository.DeleteLecturer((int)id);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var lecturer = await _lecturerRepository.Lecturers.Include(x => x.Courses).FirstOrDefaultAsync(s => s.Id == id);
            if (lecturer == null)
            {
                return NotFound();
            }
            return View(lecturer);
        }
    }

}

Controllers/StudentController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SchoolApp.Data.Abstract;
using SchoolApp.Entity;

namespace SchoolApp.Controllers
{
    public class StudentController : Controller
    {
        private IStudentRepository _studentRepository;

        public StudentController(IStudentRepository studentRepository)
        {
            _studentRepository = studentRepository;

        }

        public async Task<IActionResult> Index()
        {
            return View(await _studentRepository.Students.ToListAsync());
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(Student student)
        {
            if (ModelState.IsValid)
            {
                await _studentRepository.CreateStudent(student);
                return RedirectToAction("Index");
            }
            return View(student);
        }
        [HttpGet]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var student = await _studentRepository.Students.FirstOrDefaultAsync(s => s.Id == id);
            if (student == null)
            {
                return NotFound();
            }
            return View(student);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(Student student)
        {
            if (ModelState.IsValid)
            {
                await _studentRepository.EditStudent(student);
                return RedirectToAction("Index");
            }
            return View(student);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            await _studentRepository.DeleteStudent((int)id);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var student = await _studentRepository.Students.Include(x => x.Enrollments).ThenInclude(x => x.Course).FirstOrDefaultAsync(s => s.Id == id);
            if (student == null)
            {
                return NotFound();
            }
            return View(student);
        }


    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SchoolApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SchoolApp.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/lib/font-awesome/css/all.min.css" />
    <link rel="stylesheet" href="~/css/button.css" asp-append-version="true" />
</head>

<body>
    <nav
        class="navbar sticky-top navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SchoolApp</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Student"
                            asp-action="Index">Students</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Lecturer"
                            asp-action="Index">Lecturers</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Course" asp-action="Index">Courses</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Enrollment"
                            asp-action="Index">Enrollements</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>